#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/registry/internal-functions"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

registry-post-release-hook() {
  declare desc="pushes an app after a release to the docker registry"
  declare APP="$1"

  if [[ "$(fn-registry-enabled "$APP")" == "false" ]]; then
    return 0
  fi

  dokku_log_info1 "Checking if we should push the image to registry" 
  dokku_log_info1 "Checking if we should push the image to registry"
  if [[ "$(fn-registry-push-image "$APP")" == "false" ]]; then
    dokku_log_info1 "Pushing image to registry has been skipped"
    return 0
  else 
    dokku_log_info1 "Pushing image to registry for $APP"
  fi

  dokku_log_info1 "Pushing image to registry"
  fn-registry-tag-increment "$APP"
  fn-registry-push "$APP" "$(fn-registry-tag-latest-local "$APP")"
}

registry-post-release-hook "$@"
